name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Ejecucion Pruebas SAST
      run: echo "Ejecucion de Pruebas SAST"
      
    - name: Crear archivo de credenciales
      run: echo 'Creando archivo...'
      
    - name: Setup Docker build
      uses: docker/setup-buildx-action@v1

    - name: Docker build image
      uses: docker/build-push-action@v2
      with:       
       tags: devops_ws_:$(date +%s)
       file: ./Dockerfile.prod
