name: My pipeline

on:
  push:
    branches: ["master", "feature/*", "hotfix/*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecucion Pruebas SAST
        run: echo "Ejecucion de Pruebas SAST"

      - name: Crear archivo de credenciales
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
        run: |
          touch credentials.ini
          echo [credentials] >> credentials.ini
          echo username="$username" >> credentials.ini
          echo password="$password" >> credentials.ini
          cat credentials.ini
        shell: bash

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Tag
        id: date
        run: echo "::set-output name=date::$(date +%s)"

      - name: Setup Docker build
        uses: docker/setup-buildx-action@v1

      - name: Docker build image
        uses: docker/build-push-action@v2
        with:
          tags: devops_ws:v1.${{ github.run_number }}
          file: ./Dockerfile
