name: PR Pipeline

on:
  pull_request:
    branches: ["master", "feature/*", "hotfix/*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecucion Pruebas SAST
        run: echo "Ejecucion de Pruebas SAST"

      - name: Comprobar requisitos
        if: ${{ hashFiles('allow_pull_request/') != '' }}        
        run: |
          echo 'Testing...'
        shell: bash